package test;

public class ShowImage {
    static void showImage(int option){
        switch (option){
            case 1:
        System.out.println("\n");
        System.out.println("                                      |\n");
        System.out.println("                                     /|\n");
        System.out.println("                                   ,' |\n");
        System.out.println("                                  .   |\n");
        System.out.println("                                    | |\n");
        System.out.println("                                 ' '| |\n");
        System.out.println("                                / / | |\n");
        System.out.println("       _,.-\"\"--._              / /  | |\n");
        System.out.println("     ,'          `.           j '   ' '\n");
        System.out.println("   ,'              `.         ||   / ,                         ___..--,\n");
        System.out.println("  /                  \\        ' `.'`.-.,-\".  .       _..---\"\"'' __, ,'\n");
        System.out.println(" /                    \\        \\` .\"`      `\"'\\   ,'\"_..--''\"\"\"'.'.'\n");
        System.out.println(".                      .      .'-'             \\,' ,'         ,','\n");
        System.out.println("|                      |      ,`               ' .`         .' /\n");
        System.out.println("|                      |     /          ,\"`.  ' `-. _____.-' .'\n");
        System.out.println("'                      |..---.|,\".      | | .  .-'\"\"   __.,-'\n");
        System.out.println(" .                   ,'       ||,|      |.' |    |\"\"`'\"\n");
        System.out.println("  `-._   `._.._____  |        || |      `._,'    |\n");
        System.out.println("      `.   .       `\".     ,'\"| \"  `'           ,+.\n");
        System.out.println("        \\  '         |    '   |   .....        .'  `.\n");
        System.out.println("         .'          '     7  \".              ,'     \\\n");
        System.out.println("                   ,'      |    `..        _,'      F\n");
        System.out.println("                  .        |,      `'----''         |\n");
        System.out.println("                  |      ,\"j  /                   | '\n");
        System.out.println("                  `     |  | .                 | `,'\n");
        System.out.println("                   .    |  `.|                 |/\n");
        System.out.println("                    `-..'   ,'                .'\n");
        System.out.println("                            | \\             ,''\n");
        System.out.println("                            |  `,'.      _,' /\n");
        System.out.println("                            |    | ^.  .'   /\n");
        System.out.println("                             `-'.' j` V    /\n");
        System.out.println("                                   |      /\n");
        System.out.println("                                   |     /\n");
        System.out.println("                                   |   ,'\n");
        System.out.println("                                    `\"\"\n");
            break;
            case 2:
            System.out.println("\n");
            System.out.println("\n");
            System.out.println("                                 __.--.._,-'\"\"-.\n");
            System.out.println("                              ,-' .' ,'  .-\"''-.`.       .--.\n");
            System.out.println("                            ,'    |  |  '`-.    \\ \\       `-.|\n");
            System.out.println("                           /       .   /    `.   \\ \\        ||\n");
            System.out.println("                          /         `..`.    `.   \\ .       ||\n");
            System.out.println("                         /        . .    `.    \\   . .      '.\n");
            System.out.println("                .\"-.    .  ,\"\"'-. | |      \\    \\   `.`.__,'.'\n");
            System.out.println("                 `. `. .   |     `. |       \\    .    `-..-'\n");
            System.out.println("       _______     .  `|   |   '   .'        .   |...--._\n");
            System.out.println("       `.     `\"--.'   '    .      | .        .  |\"\"''\"-._\"-._\n");
            System.out.println("         `.             \\    `-._..'. .       |  |---.._  `-.__\"-..\n");
            System.out.println("    -.     `.           |\\           `.`      |  |'`-.  `-._   +\"-'\n");
            System.out.println("    `.`.     `-.        | `            .`.       | `. `.    `,\"\n");
            System.out.println("      `.`.      `.      |  '.           ` `      `.  \\  `   /\n");
            System.out.println("      | `.`.    __`.    |`/  `.     ...  `.`.     |   `.   .\n");
            System.out.println("      |   \\ .  `._      | `. / `. .'.' |   \\ \\    |     \\  |\n");
            System.out.println("      |.   ` \\    `-.   |   \\   .'.'/' |    \\ \\   |      ._'\n");
            System.out.println("      | `.  `.\\      `. |    \\ / , '.  |_    . \\  '-.\n");
            System.out.println("     ,     .  .\\       `|     . ' / |  | `-...\\ \\'   `._\n");
            System.out.println("     `.     `.  \\       |.    '/ .  |  |       ' .      `-.\n");
            System.out.println("      .`._    \\` \\      | `. /'  '  |  |       | |       ,.'\n");
            System.out.println("       .  `-.  \\`.\\    ,|   //  '   |  |__  .' | |      |\n");
            System.out.println("       |     `._`| `--' `  //  .    |  '  `\"  /| |   . -'\n");
            System.out.println("       '        `|       `//   '    |   .    / | |   |\n");
            System.out.println("      /....._____|       //   .  ___|   |   /  | |  ,|\n");
            System.out.println("     .         _.'      /, _.--\"'-._ `\".| ,'   | |.'\n");
            System.out.println("     |      _,' / ___   `-'.        `. _|'     |,\n");
            System.out.println("     |  _,-\"  ,'.'   `-.._  `.      _,'         `\n");
            System.out.println("     '-\"   _,','          \"- ....--'\n");
            System.out.println("    /  _.-\"_.'\n");
            System.out.println("   /_,'_,-'\n");
            System.out.println(" .'_.-'\n");
            System.out.println(" '\"\n");
            break;

            case 3:
            System.out.println("               _,........__\n");
            System.out.println("            ,-'            \"`-.\n");
            System.out.println("          ,'                   `-.\n");
            System.out.println("        ,'                        \\\n");
            System.out.println("      ,'                           .\n");
            System.out.println("      .'\\               ,\"\".       `\n");
            System.out.println("     ._.'|             / |  `       \\\n");
            System.out.println("     |   |            `-.'  ||       `.\n");
            System.out.println("     |   |            '-._,'||       | \\\n");
            System.out.println("     .`.,'             `..,'.'       , |`-.\n");
            System.out.println("     l                       .'`.  _/  |   `.\n");
            System.out.println("     `-.._'-   ,          _ _'   -\" \\  .     `\n");
            System.out.println("`.\"\"\"\"\"'-.`-...,---------','         `. `....__.\n");
            System.out.println(".'        `\"-..___      __,'\\          \\  \\     \\\n");
            System.out.println("\\_ .          |   `\"\"\"\"'    `.           . \\     \\\n");
            System.out.println("  `.          |              `.          |  .     L\n");
            System.out.println("    `.        |`--...________.'.        j   |     |\n");
            System.out.println("      `._    .'      |          `.     .|   ,     |\n");
            System.out.println("         `--,\\       .            `7\"\"' |  ,      |\n");
            System.out.println("            ` `      `            /     |  |      |    _,-'\"\"\"`-.\n");
            System.out.println("             \\ `.     .          /      |  '      |  ,'          `.\n");
            System.out.println("              \\  v.__  .        '       .   \\    /| /              \\\n");
            System.out.println("               \\/    `\"\"\\\"\"\"\"\"\"\"`.       \\   \\  /.''                |\n");
            System.out.println("                `        .        `._ ___,j.  `/ .-       ,---.     |\n");
            System.out.println("                ,`-.      \\         .\"     `.  |/        j     `    |\n");
            System.out.println("               /    `.     \\       /         \\ /         |     /    j\n");
            System.out.println("              |       `-.   7-.._ .          |\"          '         /\n");
            System.out.println("              |          `./_    `|          |            .     _,'\n");
            System.out.println("              `.           / `----|          |-............`---'\n");
            System.out.println("                \\          \\      |          |\n");
            System.out.println("               ,'           )     `.         |\n");
            System.out.println("                7____,,..--'      /          |\n");
            System.out.println("                                  `---.__,--.'mh\n");
        
            break;
            case 4:
            System.out.println("Snorlax is too big to go out... -.-!");
            break;
            case 5:
            System.out.println("                    __.._\n");
            System.out.println("                ,--'     \"`-._    _,.-,--------.\n");
            System.out.println("    ________ ,-'              `-\"'   /     _.-'|\n");
            System.out.println(" ,-'  '     :                       .    ,'    '\n");
            System.out.println("|    '     j      _.._              |  ,'     j\n");
            System.out.println("L   /      |    .'    `.            |.'      /\n");
            System.out.println(" \\ j       |    `.,'   |           ,'       /    _\n");
            System.out.println("  .|      ,'\\         /           '.___    / _.-\" |\n");
            System.out.println("   `    .'   `-.....-'                 `- +-'    /\n");
            System.out.println("    `. ,'                                `.     <__\n");
            System.out.println("      `.             .\\ \\                 |   ___ ,'\n");
            System.out.println("      |     | #      || |                  ,\"\"   \"`.\n");
            System.out.println("      |     | #      `'_/                   .       `.\n");
            System.out.println("     ,'     `.         ,-\"\".                L         `.\n");
            System.out.println("    /     (__)       _  \"\"\"                  :\"\"-.      .\n");
            System.out.println("   /             \\\"'u|         |/            |    \\     |\n");
            System.out.println("  .               \\  |         |           | |     |    |\n");
            System.out.println("  |     _          `-'        j           /  |     '    |\n");
            System.out.println("  L      `.                   |          /   |   ,'     '\n");
            System.out.println("   \\       `.                ,'         /    |_,'      /\n");
            System.out.println("    `.   ,.<'                `+--.    ,'     /       ,'\n");
            System.out.println("      `./`._'                 '_.`._,'      j      _,\n");
            System.out.println("        /\"'                      \"          |   _,'\n");
            System.out.println("       /   `._              .              '..-'\n");
            System.out.println("      j       `-._           `            /\n");
            System.out.println("      |        _,'`\"--........+.         /\n");
            System.out.println("      ,\"-.._,-'                 `.  .-._/\n");
            System.out.println("      '---'                       `+__,' mh\n");

            break;
            case 6:
            System.out.println("                                       ,|\n");
            System.out.println("                                       ||\n");
            System.out.println("                               ,-\"'\"\"`' `._\n");
            System.out.println("                              '----.     __`....._\n");
            System.out.println("                               `    `.  `. ;      `.\n");
            System.out.println("                                `.    `.  `   ,\"`. |\n");
            System.out.println("                                  `.  _.`._   |  ' |\n");
            System.out.println("                                  .','  ,' `.  `--'\n");
            System.out.println("                                 /.' _,'    | /\n");
            System.out.println("                                '/_.'       |.\n");
            System.out.println("                                 `---`\".    ||\n");
            System.out.println("                                       |    ||\n");
            System.out.println("                                      ,'    `|\n");
            System.out.println("                         _           /       |\n");
            System.out.println("                        ' `.        .'       |\n");
            System.out.println("                         .  `._  _,'/|       |\n");;;
            System.out.println("                        _|     \"'  / |       '\n");
            System.out.println("                    _,-' |        /  '        .\n");
            System.out.println("                 |\"'            ,'  '          \\\n");
            System.out.println("                 |   _        ,'   /            \\\n");
            System.out.println("                 ;  '        /    j              .\n");
            System.out.println("            ,\"--'    `.    .      |              |         ________\n");
            System.out.println("            `.   -.       / '     |              |   _,-\"\"'   __.._\"`-._\n");
            System.out.println("             ,' ,-.`-.__.' /      '              |.-'  _..--'\"       _.-'\n");
            System.out.println("             \\.'   `-.___.'      ,               '__.-\"           _.'\n");
            System.out.println("             /        _..--    . |              /               ,'\n");
            System.out.println("           ,`      .-'         | |           _,'._          _,-'\n");
            System.out.println("       _,-'      ,'           .' '       _.-'     \"-.....-\"'\n");
            System.out.println("     ,'     __ ,'          _.'  /  __..-'\n");
            System.out.println("   ,' _.-\"\"'  /         _.'  _.'-\"'\n");
            System.out.println("  '-'\"       /      _.-' _.-\"\n");
            System.out.println("            /    _.' _.-'\n");
            System.out.println("           .   .'_.-'\n");
            System.out.println("           | ,'.'\n");
            System.out.println("           | .`\n");
            System.out.println("            `\n");
            break;
            case 7:
            System.out.println("                 .\"-,.__\n");
            System.out.println("                 `.     `.  ,\n");
            System.out.println("              .--'  .._,'\"-' `.\n");
            System.out.println("             .    .'         `'\n");
            System.out.println("             `.   /          ,'\n");
            System.out.println("               `  '--.   ,-\"'\n");
            System.out.println("                `\"`   |  \\\n");
            System.out.println("                   -. \\, |\n");
            System.out.println("                    `--Y.'      ___.\n");
            System.out.println("                         \\     L._, \\\n");
            System.out.println("               _.,        `.   <  <\\                _\n");
            System.out.println("             ,' '           `, `.   | \\            ( `\n");
            System.out.println("          ../, `.            `  |    .\\`.           \\ \\_\n");
            System.out.println("         ,' ,..  .           _.,'    ||\\l            )  '\".\n");
            System.out.println("        , ,'   \\           ,'.-.`-._,'  |           .  _._`.\n");
            System.out.println("      ,' /      \\ \\        `' ' `--/   | \\          / /   ..\\\n");
            System.out.println("    .'  /        \\ .         |\\__ - _ ,'` `        / /     `.`.\n");
            System.out.println("    |  '          ..         `-...-\"  |  `-'      / /        . `.\n");
            System.out.println("    | /           |L__           |    |          / /          `. `.\n");
            System.out.println("   , /            .   .          |    |         / /             ` `\n");
            System.out.println("  / /          ,. ,`._ `-_       |    |  _   ,-' /               ` \\\n");
            System.out.println(" / .           \\\"`_/. `-_ \\_,.  ,'    +-' `-'  _,        ..,-.    \\`.\n");
            System.out.println(".  '         .-f    ,'   `    '.       \\__.---'     _   .'   '     \\ \\\n");
            System.out.println("' /          `.'    l     .' /          \\..      ,_|/   `.  ,'`     L`\n");
            System.out.println("|'      _.-\"\"` `.    \\ _,'  `            \\ `.___`.'\"`-.  , |   |    | \\\n");
            System.out.println("||    ,'      `. `.   '       _,...._        `  |    `/ '  |   '     .|\n");
            System.out.println("||  ,'          `. ;.,.---' ,'       `.   `.. `-'  .-' /_ .'    ;_   ||\n");
            System.out.println("|| '              V      / /           `   | `   ,'   ,' '.    !  `. ||\n");
            System.out.println("||/            _,-------7 '              . |  `-'    l         /    `||\n");
            System.out.println(". |          ,' .-   ,' ||               | .-.        `.      .'     ||\n");
            System.out.println(" `'        ,'    `\".'    |               |    `.        '. -.'       `'\n");
            System.out.println("          /      ,'      |               |,'    \\-.._,.'/'\n");
            System.out.println("          .     /        .               .       \\    .''\n");
            System.out.println("        .`.    |         `.             /         :_,'.'\n");
            System.out.println("          \\ `...\\   _     ,'-.        .'         /_.-'\n");
            System.out.println("           `-.__ `,  `'   .  _.>----''.  _  __  /\n");
            System.out.println("                .'        /\"'          |  \"'   '_\n");
            System.out.println("               /_|.-'\\ ,\".             '.'`__'-( \\\n");
            System.out.println("                 / ,\"'\"\\,'               `/  `-.|\" mh\n");

            break;
            case 8:
            System.out.println("                                           /\n");
            System.out.println("                        _,.------....___,.' ',.-.\n");
            System.out.println("                     ,-'          _,.--\"        |\n");
            System.out.println("                   ,'         _.-'              .\n");
            System.out.println("                  /   ,     ,'                   `\n");
            System.out.println("                 .   /     /                     ``.\n");
            System.out.println("                 |  |     .                       \\.\\\n");
            System.out.println("       ____      |___._.  |       __               \\ `.\n");
            System.out.println("     .'    `---\"\"       ``\"-.--\"'`  \\               .  \\\n");
            System.out.println("    .  ,            __               `              |   .\n");
            System.out.println("    `,'         ,-\"'  .               \\             |    L\n");
            System.out.println("   ,'          '    _.'                -._          /    |\n");
            System.out.println("  ,`-.    ,\".   `--'                      >.      ,'     |\n");
            System.out.println(" . .'\\'   `-'       __    ,  ,-.         /  `.__.-      ,'\n");
            System.out.println(" ||:, .           ,'  ;  /  / \\ `        `.    .      .'/\n");
            System.out.println(" j|:D  \\          `--'  ' ,'_  . .         `.__, \\   , /\n");
            System.out.println("/ L:_  |                 .  \"' :_;                `.'.'\n");
            System.out.println(".    \"\"'                  \"\"\"\"\"'                    V\n");
            System.out.println(" `.                                 .    `.   _,..  `\n");
            System.out.println("   `,_   .    .                _,-'/    .. `,'   __  `\n");
            System.out.println("    ) \\`._        ___....----\"'  ,'   .'  \\ |   '  \\  .\n");
            System.out.println("   /   `. \"`-.--\"'         _,' ,'     `---' |    `./  |\n");
            System.out.println("  .   _  `\"\"'--.._____..--\"   ,             '         |\n");
            System.out.println("  | .\" `. `-.                /-.           /          ,\n");
            System.out.println("  | `._.'    `,_            ;  /         ,'          .\n");
            System.out.println(" .'          /| `-.        . ,'         ,           ,\n");
            System.out.println(" '-.__ __ _,','    '`-..___;-...__   ,.'\\ ____.___.'\n");
            System.out.println(" `\"^--'..'   '-`-^-'\"--    `-^-'`.''\"\"\"\"\"`.,^.`.--' mh\n");
            System.out.println("\n");
            System.out.println("\n");
            break;
            case 9:
            System.out.println("                                             ,-.\n");
            System.out.println("                                          _.|  '\n");
            System.out.println("                                        .'  | /\n");
            System.out.println("                                      ,'    |'\n");
            System.out.println("                                     /      /\n");
            System.out.println("                       _..----\"\"---.'      /\n");
            System.out.println(" _.....---------...,-\"\"                  ,'\n");
            System.out.println(" `-._  \\                                /\n");
            System.out.println("     `-.+_            __           ,--. .\n");
            System.out.println("          `-.._     .:  ).        (`--\"| \\\n");
            System.out.println("               7    | `\" |         `...'  \\\n");
            System.out.println("               |     `--'     '+\"        ,\". ,\"\"-\n");
            System.out.println("               |   _...        .____     | |/    '\n");
            System.out.println("          _.   |  .    `.  '--\"   /      `./     j\n");
            System.out.println("         \\' `-.|  '     |   `.   /        /     /\n");
            System.out.println("         '     `-. `---\"      `-\"        /     /\n");
            System.out.println("          \\       `.                  _,'     /\n");
            System.out.println("           \\        `                        .\n");
            System.out.println("            \\                                j\n");
            System.out.println("             \\                              /\n");
            System.out.println("              `.                           .\n");
            System.out.println("                +                          \\\n");
            System.out.println("                |                           L\n");
            System.out.println("                |                           |\n");
            System.out.println("                |  _ /,                     |\n");
            System.out.println("                | | L)'..                   |\n");
            System.out.println("                | .    | `                  |\n");
            System.out.println("                '  \\'   L                   '\n");
            System.out.println("                 \\  \\   |                  j\n");
            System.out.println("                  `. `__'                 /\n");
            System.out.println("                _,.--.---........__      /\n");
            System.out.println("               ---.,'---`         |   -j\"\n");
            System.out.println("                .-'  '....__      L    |\n");
            System.out.println("              \"\"--..    _,-'       \\ l||\n");
            System.out.println("                  ,-'  .....------. `||'\n");
            System.out.println("               _,'                /\n");
            System.out.println("             ,'                  /\n");
            System.out.println("            '---------+-        /\n");
            System.out.println("                     /         /\n");
            System.out.println("                   .'         /\n");
            System.out.println("                 .'          /\n");
            System.out.println("               ,'           /\n");
            System.out.println("             _'....----\"\"\"\"\" mh\n");

            break;
        }
   
    }
}